### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by tekunotri** [TechnoSL/middle-mann-tf2c#1]
- [x] fix vip
- [x] fix menu fonts killing themselves for no reason
- [x] 4 team stuff (mismatched materials, discolored meters, etc.)
- [x] fix overlaps (engineer targetid + demo sticky charge meter + getting healed overlap)
- [x] reimplement most hud elements.
- [x] check if vip works on reimplemented scoreboard
